export PATH="$PATH:${HOME}/code/ted/infrastructure/bin"

alias rvminstall='rvm install `cat .ruby-version`'
alias ted='cd ~/code/ted'
alias fomo='cd ~/code/ted/fomoconf'
alias twt='cd ~/code/ted/twt-checkin'
alias ems='cd ~/code/ted/ems'
alias concierge='cd ~/code/ted/concierge'
alias idea='cd ~/code/ted/tedster-lounge'
alias pwall='cd ~/code/ted/program-wall'
alias becstag='bundle exec cap staging deploy'
alias becprod='bundle exec cap production deploy'
alias chewbp='chewbacca buildpush'
alias chewstag='chewbacca deploy -e staging'
alias chewprod='chewbacca deploy -e production'
